### ISSUE TITLE
Check failed: exports->Lookup(name).IsTheHole(isolate)

### ISSUE THREAD

**Issue by nair-sumesh** [ui5-community/wdi5#348] opened 2022-09-22 14:28 UTC
**Describe the bug**
It is not possible to use "wdio-ui5-service" with cucumber framework.

**To Reproduce**

1. Generate a new wdio test using he cmd ```npx wdio config```
     <img width="986" alt="image" src="https://user-images.githubusercontent.com/12034160/191772528-d817f76e-2572-4724-b192-c10091c0aaf7.png">
2. Execute the command  ```npx wdio run ./wdio.conf.js```

**Expected behavior**
Sample Cucumber feature test should run successfully.

**Logs/Console Output**
```shell
2022-09-22T10:01:55.476Z INFO @wdio/cli:launcher: Run onPrepare hook
2022-09-22T10:01:55.477Z INFO chromedriver: Start Chromedriver (/Users/userName/git/projectName/node_modules/chromedriver/lib/chromedriver/chromedriver) with args --port=9515 --url-base=/
2022-09-22T10:01:55.493Z INFO chromedriver: Starting ChromeDriver 105.0.5195.52 (412c95e518836d8a7d97250d62b29c2ae6a26a85-refs/branch-heads/5195@{#853}) on port 9515
2022-09-22T10:01:55.493Z INFO chromedriver: Only local connections are allowed.
2022-09-22T10:01:55.493Z INFO chromedriver: Please see https://chromedriver.chromium.org/security-considerations for suggestions on keeping ChromeDriver safe.
2022-09-22T10:01:55.493Z INFO chromedriver: ChromeDriver was started successfully.
2022-09-22T10:01:55.590Z INFO @wdio/cli:launcher: Run onWorkerStart hook
2022-09-22T10:01:55.591Z INFO @wdio/local-runner: Start worker 0-0 with arg: run,./wdio.conf.js
[0-0] 2022-09-22T10:01:55.875Z INFO @wdio/local-runner: Run worker command: run
[0-0] 2022-09-22T10:01:56.216Z INFO wdio-multiple-cucumber-html-reporter: The 'jsonFolder' was not set, it has been set to the default '.tmp/json/'
[0-0] 2022-09-22T10:01:56.216Z INFO wdio-multiple-cucumber-html-reporter: The 'language' was not set, it has been set to the default 'en'
[0-0] 2022-09-22T10:01:56.216Z INFO wdio-multiple-cucumber-html-reporter: The 'reportFilePerRetry' was not set, it has been set to the default 'true'
[0-0] 
[0-0] 
[0-0] #
[0-0] # Fatal error in , line 0
[0-0] # Check failed: exports->Lookup(name).IsTheHole(isolate).
[0-0] #
[0-0] #
[0-0] #
[0-0] #FailureMessage Object: 0x16f3f67c8
[0-0]  1: 0x100b0b3b4 node::NodePlatform::GetStackTracePrinter()::$_3::__invoke() [/usr/local/bin/node]
[0-0]  2: 0x1018a2b14 V8_Fatal(char const*, ...) [/usr/local/bin/node]
[0-0]  3: 0x100fc51a0 v8::internal::SyntheticModule::FinishInstantiate(v8::internal::Isolate*, v8::internal::Handle<v8::internal::SyntheticModule>) [/usr/local/bin/node]
[0-0]  4: 0x100f7020c v8::internal::Module::Instantiate(v8::internal::Isolate*, v8::internal::Handle<v8::internal::Module>, v8::Local<v8::Context>, v8::MaybeLocal<v8::Module> (*)(v8::Local<v8::Context>, v8::Local<v8::String>, v8::Local<v8::FixedArray>, v8::Local<v8::Module>), v8::MaybeLocal<v8::Module> (*)(v8::Local<v8::Context>, v8::Local<v8::String>, v8::Local<v8::Module>)) [/usr/local/bin/node]
[0-0]  5: 0x100bf8b44 v8::Module::InstantiateModule(v8::Local<v8::Context>, v8::MaybeLocal<v8::Module> (*)(v8::Local<v8::Context>, v8::Local<v8::String>, v8::Local<v8::FixedArray>, v8::Local<v8::Module>)) [/usr/local/bin/node]
[0-0]  6: 0x100a7aff4 node::loader::ModuleWrap::Instantiate(v8::FunctionCallbackInfo<v8::Value> const&) [/usr/local/bin/node]
[0-0]  7: 0x100c5c214 v8::internal::FunctionCallbackArguments::Call(v8::internal::CallHandlerInfo) [/usr/local/bin/node]
[0-0]  8: 0x100c5bd0c v8::internal::MaybeHandle<v8::internal::Object> v8::internal::(anonymous namespace)::HandleApiCallHelper<false>(v8::internal::Isolate*, v8::internal::Handle<v8::internal::HeapObject>, v8::internal::Handle<v8::internal::HeapObject>, v8::internal::Handle<v8::internal::FunctionTemplateInfo>, v8::internal::Handle<v8::internal::Object>, v8::internal::BuiltinArguments) [/usr/local/bin/node]
[0-0]  9: 0x100c5b598 v8::internal::Builtin_HandleApiCall(int, unsigned long*, v8::internal::Isolate*) [/usr/local/bin/node]
[0-0] 10: 0x10139accc Builtins_CEntry_Return1_DontSaveFPRegs_ArgvOnStack_BuiltinExit [/usr/local/bin/node]
[0-0] 11: 0x10572f96c 
[0-0] 12: 0x10572c6a8 
[0-0] 13: 0x105711054 
[0-0] 14: 0x105724898 
[0-0] 15: 0x105719528 
[0-0] 16: 0x105717b9c 
[0-0] 17: 0x10132e818 Builtins_InterpreterEntryTrampoline [/usr/local/bin/node]
[0-0] 18: 0x105729510 
[0-0] 19: 0x1057a2be4 
[0-0] 20: 0x10572f3bc 
[0-0] 21: 0x1057a35e8 
[0-0] 22: 0x10572064c 
[0-0] 23: 0x105724bd0 
[0-0] 24: 0x105719528 
[0-0] 25: 0x105717b9c 
[0-0] 26: 0x10132e818 Builtins_InterpreterEntryTrampoline [/usr/local/bin/node]
[0-0] 27: 0x105729510 
[0-0] 28: 0x1057a2be4 
[0-0] 29: 0x10572f3bc 
[0-0] 30: 0x1057a35e8 
[0-0] 31: 0x10572064c 
[0-0] 32: 0x105724bd0 
[0-0] 33: 0x105719528 
[0-0] 34: 0x105717b9c 
[0-0] 35: 0x10132e818 Builtins_InterpreterEntryTrampoline [/usr/local/bin/node]
[0-0] 36: 0x105729510 
[0-0] 37: 0x1057a2be4 
[0-0] 38: 0x10572f3bc 
[0-0] 39: 0x1057a35e8 
[0-0] 40: 0x10572064c 
[0-0] 41: 0x105724bd0 
[0-0] 42: 0x105719528 
[0-0] 43: 0x105717b9c 
[0-0] 44: 0x10132e818 Builtins_InterpreterEntryTrampoline [/usr/local/bin/node]
[0-0] 45: 0x105729510 
[0-0] 46: 0x1057a2be4 
[0-0] 47: 0x10572f3bc 
[0-0] 48: 0x1057a35e8 
[0-0] 49: 0x10572064c 
[0-0] 50: 0x105724bd0 
[0-0] 51: 0x105719528 
[0-0] 52: 0x105717b9c 
[0-0] 53: 0x10132e818 Builtins_InterpreterEntryTrampoline [/usr/local/bin/node]
[0-0] 54: 0x105729510 
[0-0] 55: 0x1057a2be4 
[0-0] 56: 0x10572f3bc 
[0-0] 57: 0x1057a35e8 
[0-0] 58: 0x10572064c 
[0-0] 59: 0x105724bd0 
[0-0] 60: 0x105719528 
[0-0] 61: 0x105717b9c 
[0-0] 62: 0x10132e818 Builtins_InterpreterEntryTrampoline [/usr/local/bin/node]
[0-0] 63: 0x10132e818 Builtins_InterpreterEntryTrampoline [/usr/local/bin/node]
[0-0] 64: 0x10132e818 Builtins_InterpreterEntryTrampoline [/usr/local/bin/node]
[0-0] 65: 0x10135de14 Builtins_AsyncFunctionAwaitResolveClosure [/usr/local/bin/node]
[0-0] 66: 0x1013e2c78 Builtins_PromiseFulfillReactionJob [/usr/local/bin/node]
[0-0] 67: 0x1013501f4 Builtins_RunMicrotasks [/usr/local/bin/node]
[0-0] 68: 0x10132c4e4 Builtins_JSRunMicrotasksEntry [/usr/local/bin/node]
[0-0] 69: 0x100cfefcc v8::internal::(anonymous namespace)::Invoke(v8::internal::Isolate*, v8::internal::(anonymous namespace)::InvokeParams const&) [/usr/local/bin/node]
[0-0] 70: 0x100cff400 v8::internal::(anonymous namespace)::InvokeWithTryCatch(v8::internal::Isolate*, v8::internal::(anonymous namespace)::InvokeParams const&) [/usr/local/bin/node]
[0-0] 71: 0x100cff4ec v8::internal::Execution::TryRunMicrotasks(v8::internal::Isolate*, v8::internal::MicrotaskQueue*, v8::internal::MaybeHandle<v8::internal::Object>*) [/usr/local/bin/node]
[0-0] 72: 0x100d22128 v8::internal::MicrotaskQueue::RunMicrotasks(v8::internal::Isolate*) [/usr/local/bin/node]
[0-0] 73: 0x100d229bc v8::internal::MicrotaskQueue::PerformCheckpoint(v8::Isolate*) [/usr/local/bin/node]
[0-0] 74: 0x100c5c214 v8::internal::FunctionCallbackArguments::Call(v8::internal::CallHandlerInfo) [/usr/local/bin/node]
[0-0] 75: 0x100c5bd0c v8::internal::MaybeHandle<v8::internal::Object> v8::internal::(anonymous namespace)::HandleApiCallHelper<false>(v8::internal::Isolate*, v8::internal::Handle<v8::internal::HeapObject>, v8::internal::Handle<v8::internal::HeapObject>, v8::internal::Handle<v8::internal::FunctionTemplateInfo>, v8::internal::Handle<v8::internal::Object>, v8::internal::BuiltinArguments) [/usr/local/bin/node]
[0-0] 76: 0x100c5b598 v8::internal::Builtin_HandleApiCall(int, unsigned long*, v8::internal::Isolate*) [/usr/local/bin/node]
[0-0] 77: 0x10139accc Builtins_CEntry_Return1_DontSaveFPRegs_ArgvOnStack_BuiltinExit [/usr/local/bin/node]
[0-0] 78: 0x10132e818 Builtins_InterpreterEntryTrampoline [/usr/local/bin/node]
[0-0] 79: 0x10132c60c Builtins_JSEntryTrampoline [/usr/local/bin/node]
[0-0] 80: 0x10132c2a4 Builtins_JSEntry [/usr/local/bin/node]
[0-0] 81: 0x100cff004 v8::internal::(anonymous namespace)::Invoke(v8::internal::Isolate*, v8::internal::(anonymous namespace)::InvokeParams const&) [/usr/local/bin/node]
[0-0] 82: 0x100cfe698 v8::internal::Execution::Call(v8::internal::Isolate*, v8::internal::Handle<v8::internal::Object>, v8::internal::Handle<v8::internal::Object>, int, v8::internal::Handle<v8::internal::Object>*) [/usr/local/bin/node]
[0-0] 83: 0x100c0bd24 v8::Function::Call(v8::Local<v8::Context>, v8::Local<v8::Value>, int, v8::Local<v8::Value>*) [/usr/local/bin/node]
[0-0] 84: 0x1009fdd00 node::InternalCallbackScope::Close() [/usr/local/bin/node]
[0-0] 85: 0x1009fdfc8 node::InternalMakeCallback(node::Environment*, v8::Local<v8::Object>, v8::Local<v8::Object>, v8::Local<v8::Function>, int, v8::Local<v8::Value>*, node::async_context) [/usr/local/bin/node]
[0-0] 86: 0x100a128f0 node::AsyncWrap::MakeCallback(v8::Local<v8::Function>, int, v8::Local<v8::Value>*) [/usr/local/bin/node]
[0-0] 87: 0x100b4f1dc node::StreamBase::CallJSOnreadMethod(long, v8::Local<v8::ArrayBuffer>, unsigned long, node::StreamBase::StreamBaseJSChecks) [/usr/local/bin/node]
[0-0] 88: 0x100b50c00 node::EmitToJSStreamListener::OnStreamRead(long, uv_buf_t const&) [/usr/local/bin/node]
[0-0] 89: 0x100b54d1c node::LibuvStreamWrap::OnUvRead(long, uv_buf_t const*) [/usr/local/bin/node]
[0-0] 90: 0x100b55400 node::LibuvStreamWrap::ReadStart()::$_1::__invoke(uv_stream_s*, long, uv_buf_t const*) [/usr/local/bin/node]
[0-0] 91: 0x101319fa0 uv__stream_io [/usr/local/bin/node]
[0-0] 92: 0x1013220a8 uv__io_poll [/usr/local/bin/node]
[0-0] 93: 0x1013107ec uv_run [/usr/local/bin/node]
[0-0] 94: 0x1009fe6d4 node::SpinEventLoop(node::Environment*) [/usr/local/bin/node]
[0-0] 95: 0x100ae5328 node::NodeMainInstance::Run(int*, node::Environment*) [/usr/local/bin/node]
[0-0] 96: 0x100ae5008 node::NodeMainInstance::Run() [/usr/local/bin/node]
[0-0] 97: 0x100a81a40 node::Start(int, char**) [/usr/local/bin/node]
[0-0] 98: 0x1055e908c 
[0-0] FAILED
2022-09-22T10:01:56.456Z INFO @wdio/cli:launcher: Run onWorkerEnd hook
2022-09-22T10:01:56.456Z INFO @wdio/cli:launcher: Run onComplete hook

Spec Files:      0 passed, 1 failed, 1 total (100% completed) in 00:00:01 

2022-09-22T10:01:56.457Z INFO @wdio/local-runner: Shutting down spawned worker
2022-09-22T10:01:56.709Z INFO @wdio/local-runner: Waiting for 0 to shut down gracefully
2022-09-22T10:01:56.711Z INFO @wdio/local-runner: shutting down
```

**Runtime Env (please complete the following information):**

- `wdi5/wdio-ui5-service`-version: 1.1.5
- `UI5` version: Doesn't matter
- `wdio`-version (output of `wdio --version`): [e.g. 7.16.12]
- `node`-version (output of `node --version`): v16.17.0
- OS: macOS 12.6
- Browser + Version chrome Version 105.0.5195.125 (Official Build) (arm64)

Regards,
-SN

**Comment by vobu** [comment] 2022-09-22 15:09
Hi, this doesn't look like it's related to `wdi5` since the error messages don't originate anywhere near `wdi5`, but seem to stem from chrome's v8 engine (`chromedriver`), not from the Node.js scope. 
What happens if you try to start `chromedriver` from the cmd line?

**Comment by arnaudbuchholz-sap** [comment] 2022-09-22 19:41
We investigated a bit and it seems to be related to some wdi5 logging core that, when requires, breaks node... very strange issue indeed

**Comment by Siolto** [comment] 2022-09-22 20:07
I just tried to reproduce your issue. But for me it seems to work perfectly fine:
```shell
npx wdio config

=========================
WDIO Configuration Helper
=========================

? Where is your automation backend located? On my local machine
? Which framework do you want to use? cucumber
? Do you want to use a compiler? No!
? Where are your feature files located? ./features/**/*.feature
? Where are your step definitions located? ./features/step-definitions/steps.js
? Do you want WebdriverIO to autogenerate some test files? Yes
? Do you want to use page objects (https://martinfowler.com/bliki/PageObject.html)? Yes
? Where are your page objects located? ./features/pageobjects/**/*.js
? Which reporter do you want to use? spec, cucumber-json
? Do you want to add a plugin to your test setup? wait-for
? Do you want to add a service to your test setup? chromedriver, ui5
? What is the base url? https://sapui5.hana.ondemand.com
? Do you want me to run `npm install` Yes

Installing wdio packages:
- @wdio/local-runner
- @wdio/cucumber-framework
- @wdio/spec-reporter
- wdio-cucumberjs-json-reporter
- wdio-wait-for
- wdio-chromedriver-service
- wdio-ui5-service
- chromedriver

npx wdio run wdio.conf.js

 PASSED in chrome - /features/login.feature
2022-09-22T19:59:08.842Z INFO @wdio/cli:launcher: Run onWorkerEnd hook
2022-09-22T19:59:08.842Z INFO @wdio/cli:launcher: Run onComplete hook

 "spec" Reporter:
------------------------------------------------------------------
[chrome 105.0.5195.125 mac os x #0-0] Running: chrome (v105.0.5195.125) on mac os x
[chrome 105.0.5195.125 mac os x #0-0] Session ID: d1fce942c904c0e7f7109b04e287b2b1
[chrome 105.0.5195.125 mac os x #0-0]
[chrome 105.0.5195.125 mac os x #0-0] » /features/login.feature
[chrome 105.0.5195.125 mac os x #0-0] The Internet Guinea Pig Website
[chrome 105.0.5195.125 mac os x #0-0] As a user, I can log into the secure area
[chrome 105.0.5195.125 mac os x #0-0]    ✓ Given I am on the login page
[chrome 105.0.5195.125 mac os x #0-0]    ✓ When I login with tomsmith and SuperSecretPassword!
[chrome 105.0.5195.125 mac os x #0-0]    ✓ Then I should see a flash message saying You logged into a secure area!
[chrome 105.0.5195.125 mac os x #0-0]
[chrome 105.0.5195.125 mac os x #0-0] As a user, I can log into the secure area
[chrome 105.0.5195.125 mac os x #0-0]    ✓ Given I am on the login page
[chrome 105.0.5195.125 mac os x #0-0]    ✓ When I login with foobar and barfoo
[chrome 105.0.5195.125 mac os x #0-0]    ✓ Then I should see a flash message saying Your username is invalid!
[chrome 105.0.5195.125 mac os x #0-0]
[chrome 105.0.5195.125 mac os x #0-0] 6 passing (3.2s)


Spec Files:	 1 passed, 1 total (100% completed) in 00:00:07

2022-09-22T19:59:08.843Z INFO @wdio/local-runner: Shutting down spawned worker
2022-09-22T19:59:09.095Z INFO @wdio/local-runner: Waiting for 0 to shut down gracefully
2022-09-22T19:59:09.095Z INFO @wdio/local-runner: shutting down

```

The only difference is that I did not selected the `timeline` reporter. @nair-sumesh is your `wdio-ui5-service` version really `1.1.15`? We don't have a version like that. Our newest version currently is `0.9.13`.

Regards,
Simon

**Comment by nair-sumesh** [comment] 2022-09-22 20:15
@Siolto :The version was a typo. My bad :)
Does you conf have    ``` services: ['chromedriver','ui5'],```

**Comment by nair-sumesh** [comment] 2022-09-22 20:22
I cleaned up the Node_modules and tried again.
I still have the same error.

**Comment by Siolto** [comment] 2022-09-22 20:27
Hi @nair-sumesh,

yes I have the `ui5` service included. I even wrote a very dumb and simplistic test and it works completely fine on my site:

**steps.js**
```javascript
// not really BDD style but it works
  When("Cucumber Test", async () => {
    const selector = await browser.asControl({
        selector: {
            id: "sdk---app--headerToolbar"
        }
    })
    await expect(await selector.isInitialized()).toBeTruthy();
})
```
**feture file**
```
Feature: Cucumber Test

  Scenario Outline: Cucumber Test
    When Cucumber Test
```

```bash
[chrome 105.0.5195.125 mac os x #0-0] Running: chrome (v105.0.5195.125) on mac os x
[chrome 105.0.5195.125 mac os x #0-0] Session ID: 9e9d28c4eb3a49454dc43d81492d0047
[chrome 105.0.5195.125 mac os x #0-0]
[chrome 105.0.5195.125 mac os x #0-0] » /features/login.feature
[chrome 105.0.5195.125 mac os x #0-0] Cucumber Test
[chrome 105.0.5195.125 mac os x #0-0] Cucumber Test
[chrome 105.0.5195.125 mac os x #0-0]    ✓ When Cucumber Test
[chrome 105.0.5195.125 mac os x #0-0]
[chrome 105.0.5195.125 mac os x #0-0] 1 passing (1.7s)


Spec Files:	 1 passed, 1 total (100% completed) in 00:00:07
```

Regards,
Simon

**Comment by nair-sumesh** [comment] 2022-09-22 20:34
And are you at node version  v16.17.0.
Dumb request, but can you also try to execute with the sample code created by wdio config.

**Comment by Siolto** [comment] 2022-09-22 20:41
Yes I am at `16.17.0` and in my first answer to this issue I already executed the tests with the sample code that was generated by wdio (with wdi5 in `services` included). Could you maybe share a .zip file of a reproducible example?

**Comment by nair-sumesh** [comment] 2022-09-23 01:10
Please clone the [project](https://github.com/nair-sumesh/wdi5Cucumber)

**Comment by nair-sumesh** [comment] 2022-10-25 13:10
hey 👋

**Comment by Siolto** [comment] 2022-10-27 08:19
Hi @nair-sumesh,

sorry for the late response. The chromedriver is currently outdated so I have to update the devDependencies. But what I found in your reference project is that you don't have the required [`wdi5`](https://ui5-community.github.io/wdi5/#/configuration?id=wdi5) configuration in you `.conf.js` file. Maybe this is the reason for your errors.

Regards,
Simon

**Comment by nair-sumesh** [comment] 2022-10-27 13:56
Hi @Siolto ,

I don't think that should  be the reason.     
However, just to be sure, I have added the required wdi5 configurarion.
The issue still exists.
Please fetch the recent changes.

**Comment by sn-sap** [comment] 2022-11-23 19:29
I am keen to compare the working test for Cucumber with my version.     
Will it be possible for you to share the example which worked for you.     

Best Regards,
Sumesh Nair

**Comment by nair-sumesh** [comment] 2022-11-23 19:35
I am keen to compare the working test for Cucumber with my version.
Will it be possible for you to share the example which worked for you.

Best Regards,
Sumesh Nair

**Comment by Siolto** [comment] 2022-11-29 11:57
Hi @nair-sumesh,

after investigating a little bit more and by finally being able to reproduce your issue I probably found a solution. Could you please add [`ts-node`](https://www.npmjs.com/package/ts-node) to your development dependencies and try to run it again. At least im my case this solved the issue.

Why this dependency, in this specific combination, is needed needs to be checked.

Regards,
Simon

**Comment by nair-sumesh** [comment] 2022-11-29 13:26
Thanks @Siolto. It worked.    
Will test few more scenarios before closing this ticket.

**Comment by Siolto** [comment] 2022-11-29 14:05
@nair-sumesh 

after investigating further with @vobu, we found a name clash with the cucumber framework. We will create a fix for that and automatically close this ticket when the fix is merged.

**Comment by nair-sumesh** [comment] 2022-12-13 11:01
Just FYI, Issue still exists with
```
  "name": "wdio-ui5-service",
  "version": "1.0.4",
```

**Comment by vobu** [comment] 2022-12-13 12:38
could you please `rm package-lock.json` and `rm -rf node_modules` and try again?

**Comment by vobu** [comment] 2022-12-13 12:55
scratch that, we just verified: bug still exists. gnarf. sorry :(

**Comment by nair-sumesh** [comment] 2022-12-13 16:19
##### Some Observations
- Similar [Issue](https://github.com/nodejs/node/issues/32806)
- Another [Console ](https://github.com/ui5-community/wdi5/blob/027300e673c94f93ad85581131f1a6b6fe214169/src/lib/Logger.ts#L1) variable in Logger.ts

**Comment by nair-sumesh** [comment] 2022-12-13 20:13
With `"version": "1.0.4"`, now the mocha test also fails with same kind of error.

**Comment by vobu** [comment] 2022-12-14 06:45
ok, we‘ll pull back/revert 1.0.4 until we get this issue under control.
Thanks for staying on top and investigating, @nair-sumesh! 🙏

**Comment by vobu** [comment] 2022-12-14 07:55
deprecated `1.0.4`, b/c npm didn't allow for unpublishing :(
→ https://github.com/ui5-community/wdi5/discussions/389
→ https://twitter.com/_wdi5_/status/1602933770201489408?s=61&t=HFgk8Rob7TpJt1PDqgPuNQ
→ https://fosstodon.org/@_wdi5_/109510946057469576

**Closed** 2023-01-13 10:38 UTC
