### ISSUE TITLE
Running wdi5 tests in SAP Business Application Studio (BAS) using chromium 87.0.4280.141

### ISSUE THREAD

**Issue by gregorwolf** [ui5-community/wdi5#329] opened 2022-08-10 22:23 UTC
**Describe the bug**

I try to get wdi5 tests working in SAP BAS. I would hope that this is possible as at least chromium ist installed. This can be checked by running

```shell
$ chromium --version
Chromium 87.0.4280.141 built on Debian 10.7, running on Debian 10.8
```

The path to chromium is:

```shell
$ which chromium
/extbin/bin/chromium
```

When running:

```shell
> chromium --headless --screenshot https://bestofui5.org
```

I can also produce a screenshot:

![screenshot](https://user-images.githubusercontent.com/2639535/184030795-16df6d2b-d002-4790-ab50-1467ba263b69.png)

so I think chromium is fully functional.

**To Reproduce**

1. Clone the https://github.com/ui5-community/wdi5-workshop repository
2. run `npm i`
3. `cd fe-app`
4. adjust *fe-app/wdio.conf.js*
  ```
           browserName: "chromium",
           binary: "/extbin/bin/chromium",
  ```
5. run `npm run wdi5`and you will see the following error

```
> incidents@0.0.1 wdi5
> run-p -r serve _wdi5


> incidents@0.0.1 serve
> ui5 serve --port 8088


> incidents@0.0.1 _wdi5
> wait-on tcp:8088 && wdio run wdio.conf.js

info normalizer:translators:ui5Framework Using SAPUI5 version: 1.97.2
WARN normalizer:projectPreprocessor Dependency sap.fe.test is restricted for use by SAP internal projects only! If the project incidents is an SAP internal project, add the attribute "allowSapInternal: true" to its metadata configuration
WARN normalizer:projectPreprocessor Dependency sap.fe.templates is restricted for use by SAP internal projects only! If the project incidents is an SAP internal project, add the attribute "allowSapInternal: true" to its metadata configuration
info server:ux-fe-mockserver JSON file found for Category
info server:ux-fe-mockserver JSON file found for IncidentStatus
info server:ux-fe-mockserver JSON file found for IncidentFlow
info server:ux-fe-mockserver JSON file found for IncidentProcessTimeline
info server:ux-fe-mockserver JSON file found for Incidents
Server started
URL: http://localhost:8088
info server:ux-fe-mockserver JSON file found for Individual
info server:ux-fe-mockserver JSON file found for Priority

Execution of 1 workers started at 2022-08-10T22:03:16.950Z

SevereServiceError in "onPrepare"
SevereServiceError: 
A service failed in the 'onPrepare' hook
SevereServiceError: Couldn't start Chromedriver: timeout
Chromedriver failed to start.
    at ChromeDriverLauncher.onPrepare (/home/user/projects/wdi5-workshop/node_modules/wdio-chromedriver-service/build/launcher.js:106:13)
    at async /home/user/projects/wdi5-workshop/node_modules/@wdio/cli/build/utils.js:35:17
    at async Promise.all (index 0)
    at async Launcher.run (/home/user/projects/wdi5-workshop/node_modules/@wdio/cli/build/launcher.js:86:13)



Stopping runner...
    at /home/user/projects/wdi5-workshop/node_modules/@wdio/cli/build/utils.js:51:35
    at async Launcher.run (/home/user/projects/wdi5-workshop/node_modules/@wdio/cli/build/launcher.js:86:13)
HookError [SevereServiceError]: 
A service failed in the 'onPrepare' hook
SevereServiceError: Couldn't start Chromedriver: timeout
Chromedriver failed to start.
    at ChromeDriverLauncher.onPrepare (/home/user/projects/wdi5-workshop/node_modules/wdio-chromedriver-service/build/launcher.js:106:13)
    at async /home/user/projects/wdi5-workshop/node_modules/@wdio/cli/build/utils.js:35:17
    at async Promise.all (index 0)
    at async Launcher.run (/home/user/projects/wdi5-workshop/node_modules/@wdio/cli/build/launcher.js:86:13)



Stopping runner...
    at /home/user/projects/wdi5-workshop/node_modules/@wdio/cli/build/utils.js:51:35
    at async Launcher.run (/home/user/projects/wdi5-workshop/node_modules/@wdio/cli/build/launcher.js:86:13) {
  origin: 'onPrepare'
}
npm ERR! Lifecycle script `_wdi5` failed with error: 
npm ERR! Error: command failed 
npm ERR!   in workspace: incidents@0.0.1 
npm ERR!   at location: /home/user/projects/wdi5-workshop/fe-app 
ERROR: "_wdi5" exited with 1.
npm ERR! Lifecycle script `wdi5` failed with error: 
npm ERR! Error: command failed 
npm ERR!   in workspace: incidents@0.0.1 
npm ERR!   at location: /home/user/projects/wdi5-workshop/fe-app 
```

**Expected behavior**

Running wdi5 tests in SAP Business Application Studio (BAS) should be possible.

**Comment by Siolto** [comment] 2022-08-15 07:25
Hi Gregor,

thanks for providing such detailed information and context! We are already aware of this problem and are exchanging information with BAS colleagues. As I understand it, this is not a wdi5 problem for the time being. Apparently, certain dependencies that we need are missing in the Docker images on which we work in BAS. 

The colleagues are already looking at this. Unfortunately I can't tell you when it will be possible to start wdi5 tests in BAS. 

Regards,
Simon

**Comment by gregorwolf** [comment] 2022-08-16 10:23
Hi @Siolto ,

thank you for the follow up. Would it help if I create an customer incident? As BAS is SAP's promoted development infrastructure and wdi5 is the standard integration test tool for SAPUI5 apps now I think it should work out of the box in BAS.

Best Regards
Gregor

**Comment by Siolto** [comment] 2022-08-16 10:47
@gregorwolf definitely! I think when they also get the feedback from customers and partners that there is a major piece missing in their tooling, this could get more attention and resolved faster.

btw: UIVeri5 hast never worked either in BAS when I remember it correctly more or less for the same reasons.

Regards,
Simon

**Comment by gregorwolf** [comment] 2022-08-16 13:08
I've created SAP Support Incident 601180 / 2022

**Comment by gregorwolf** [comment] 2022-09-18 09:12
9 Votes for the request. But Status still only Submitted.

**Comment by vobu** [comment] 2022-10-20 07:12
the influence request is still open.
yet it is only in status "submitted" :(
probably @nicoschoenteich can reach out and check w/ Oliver Graeff what the plans are going forward for BAS + wdi5?

**Comment by nicoschoenteich** [comment] 2022-10-24 07:43
Hi all, This is being reviewed internally currently. Hope to have a road map item ready very soon.

**Comment by gregorwolf** [comment] 2022-11-24 07:57
14 Votes now for the influencing request.

**Comment by gregorwolf** [comment] 2023-01-06 20:37
I've tested again with the new VS Code based BAS. Unfortunately it's still the same problem:

```
user: fe-app $ npm run wdi5

> incidents@0.0.1 wdi5
> wdio run wdio.conf.js

Execution of 1 workers started at 2023-01-06T20:33:51.746Z

SevereServiceError in "onPrepare"
SevereServiceError: 
A service failed in the 'onPrepare' hook
SevereServiceError: Couldn't start Chromedriver: timeout
Chromedriver failed to start.
    at ChromeDriverLauncher.onPrepare (/home/user/projects/wdi5-workshop/ui5con2022/node_modules/wdio-chromedriver-service/build/launcher.js:106:13)
    at async /home/user/projects/wdi5-workshop/ui5con2022/node_modules/@wdio/cli/build/utils.js:35:17
    at async Promise.all (index 0)
    at async Launcher.run (/home/user/projects/wdi5-workshop/ui5con2022/node_modules/@wdio/cli/build/launcher.js:86:13)

Stopping runner...
    at /home/user/projects/wdi5-workshop/ui5con2022/node_modules/@wdio/cli/build/utils.js:51:35
    at async Launcher.run (/home/user/projects/wdi5-workshop/ui5con2022/node_modules/@wdio/cli/build/launcher.js:86:13)
HookError [SevereServiceError]: 
A service failed in the 'onPrepare' hook
SevereServiceError: Couldn't start Chromedriver: timeout
Chromedriver failed to start.
    at ChromeDriverLauncher.onPrepare (/home/user/projects/wdi5-workshop/ui5con2022/node_modules/wdio-chromedriver-service/build/launcher.js:106:13)
    at async /home/user/projects/wdi5-workshop/ui5con2022/node_modules/@wdio/cli/build/utils.js:35:17
    at async Promise.all (index 0)
    at async Launcher.run (/home/user/projects/wdi5-workshop/ui5con2022/node_modules/@wdio/cli/build/launcher.js:86:13)

Stopping runner...
    at /home/user/projects/wdi5-workshop/ui5con2022/node_modules/@wdio/cli/build/utils.js:51:35
    at async Launcher.run (/home/user/projects/wdi5-workshop/ui5con2022/node_modules/@wdio/cli/build/launcher.js:86:13) {
  origin: 'onPrepare'
}
npm ERR! Lifecycle script `wdi5` failed with error: 
npm ERR! Error: command failed 
npm ERR!   in workspace: incidents@0.0.1 
npm ERR!   at location: /home/user/projects/wdi5-workshop/ui5con2022/fe-app 
```

**Comment by pragu4** [comment] 2023-01-12 00:23
Hello Team,

Can you please provide the step to step document for simple sap ui5 application testing for vs code.

I have tried a lot of things but the issue is not resolved.

Thanks,
Pragnesh

**Comment by gregorwolf** [comment] 2023-01-12 06:26
@pragu4 does your question relate to this issue? Or do you have issues getting wdi5 to work in your local VS Code?

**Comment by gregorwolf** [comment] 2023-02-12 08:45
23 Votes now for the influencing request.

**Comment by vobu** [comment] 2023-04-01 06:25
this is about to be released, me heared...albeit with a limited scope, but still! 👍

**Comment by vobu** [comment] 2023-05-02 08:52
about to come with #459 :)

**Comment by vobu** [comment] 2023-05-04 11:16
multiple beta testers (thanks @marianfoo and @nicoschoenteich!) reported that the current BAS extension enabling wdi5 in BAS doesn't work - see https://twitter.com/mianbsp/status/1653848495839760384?s=20 and https://twitter.com/NicoSchoenteich/status/1654041518817116162?s=20

**Comment by NetaMolcho** [comment] 2023-05-04 14:34
Hi, 
Regarding https://twitter.com/NicoSchoenteich/status/1654041518817116162?s=20 problem, he just needs to create a 'profile' folder. Just write ״mkdir /tmp/profile״ in the terminal and it should run.

Regarding https://twitter.com/mianbsp/status/1653848495839760384?s=20, it seems the configuration is incorrect, if it is possible to add the configuration file, I would be happy to take a look and try to help.

**Comment by marianfoo** [comment] 2023-05-04 14:51
Here is my Config https://github.com/marianfoo/ui5-cc-excelUpload/commit/492bf5785183a65a7859f7a80e4bbeeb042476ef

**Comment by NetaMolcho** [comment] 2023-05-04 15:38
Hi @marianfoo 
I see your baseUrl is 'http://localhost:8080/index.html', but in the package.json I don't see "ui5 serve --port 8080".
are you sure that there is a running UI5 app? 
If you want, we can schedule a meeting for next week (because in Israel the weekend is already started) so we will do the scenario together and try to solve it.

**Comment by marianfoo** [comment] 2023-05-05 11:29
Hi @NetaMolcho ,
the setup is now working for me.
I had to downgrade geckodriver to `3.1.0`.
See here my changes from chrome to firefox for BAS
https://github.com/marianfoo/ui5-cc-excelUpload/pull/180/files
![image](https://user-images.githubusercontent.com/13335743/236446461-e90c3372-be83-496a-b36d-bf25bab82302.png)

**Comment by NetaMolcho** [comment] 2023-05-07 07:13
Great, thank you for the update (:

**Comment by Siolto** [comment] 2024-01-17 15:48
@vobu I think we can close this issue, right?

**Comment by vobu** [comment] 2024-01-19 07:58
well, strictly speaking `chrom`(ium) is still not working in BAS, but at least Firefox headless is...so yeah, I'll close this

**Closed by vobu** 2024-01-19 07:58 UTC
Labels: 🖊 documentation, enhancement, in Progress
